# Generated by Django 3.1.2 on 2020-10-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nature', models.CharField(choices=[('Field', 'Field'), ('Nested', 'Nested'), ('Dict', 'Dict'), ('List', 'List'), ('String', 'String'), ('UUID', 'UUID'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('DateTime', 'DateTime'), ('Url', 'Url'), ('Email', 'Email'), ('IPv4', 'IPv4')], max_length=10)),
                ('nature_id', models.IntegerField()),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('allow_none', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='IntegerNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strict', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPv4Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploded', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NestedNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude', models.CharField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='ListNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventField', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventfield')),
            ],
        ),
        migrations.CreateModel(
            name='DictNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='event.eventfield')),
                ('values', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='val', to='event.eventfield')),
            ],
        ),
    ]
