# Generated by Django 3.1.2 on 2020-10-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('validate_schema', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nature', models.CharField(choices=[('Field', 'Field'), ('Nested', 'Nested'), ('Dict', 'Dict'), ('List', 'List'), ('String', 'String'), ('UUID', 'UUID'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('DateTime', 'DateTime'), ('Url', 'Url'), ('Email', 'Email'), ('IPv4', 'IPv4')], max_length=10)),
                ('nature_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('allow_none', models.BooleanField(default=False)),
                ('validate', models.TextField(blank=True, null=True)),
                ('excluded', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='IntegerNature',
            fields=[
                ('strict', models.BooleanField(default=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IPv4Nature',
            fields=[
                ('exploded', models.BooleanField(default=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UrlNature',
            fields=[
                ('relative', models.BooleanField(default=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NestedNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='ListNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventfield')),
            ],
        ),
        migrations.CreateModel(
            name='DictNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='event.eventfield')),
                ('values', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='val', to='event.eventfield')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventfield',
            index=models.Index(fields=['event', 'name'], name='event_event_event_i_85ea86_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventfield',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_id_name'),
        ),
    ]
