# Generated by Django 3.1.2 on 2020-10-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listnature',
            old_name='eventField',
            new_name='event_field',
        ),
        migrations.AddField(
            model_name='event',
            name='validate_schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventfield',
            name='validate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
