# Generated by Django 3.1.2 on 2020-10-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201021_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfield',
            name='nature_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
