# Generated by Django 3.1.2 on 2020-10-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20201021_1157'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventfield',
            index=models.Index(fields=['event_id', 'name'], name='event_event_event_i_c5f068_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventfield',
            constraint=models.UniqueConstraint(fields=('event_id', 'name'), name='unique_id_name'),
        ),
    ]
