# Generated by Django 3.1.2 on 2020-10-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20201021_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfield',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
