# Generated by Django 3.1.2 on 2020-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventfield_excluded'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventfield',
            name='event_event_event_i_c5f068_idx',
        ),
        migrations.RenameField(
            model_name='eventfield',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='nestednature',
            old_name='event_id',
            new_name='event',
        ),
        migrations.AddIndex(
            model_name='eventfield',
            index=models.Index(fields=['event_id', 'name'], name='event_event_event_i_85ea86_idx'),
        ),
    ]
